spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      enable_lazy_load_no_trans: 'true'
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/coupon_project_spring
    username: root
    password: Meital123!
    driverClassName: com.mysql.cj.jdbc.Driver
